@jwt=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzI0NTA0OTl9.wnKRERbayTaNsaWlmuTwgRXI1k5yrQ6hQh8aWuVsAr0


###
GET http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

####
GET http://localhost:3000/artifacts/2.json
Content-Type: application/json
Authorization: Bearer {{jwt}}


#### update points
PATCH http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "points": 90
}


### login
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###
POST http://localhost:3000/artifacts.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "price_in_points": 20,
  "image_url": "https://items.jellyneo.net/layout/imgs/itemdb/mascot_sad_250.png",
  "name": "Sad Mascot"
}

