/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 cardboard.gltf
Author: sharpened (https://sketchfab.com/sharpened)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/closed-cardboard-box-free-download-c023cd16986445d880871174d7fe8623
Title: Closed Cardboard Box (Free Download)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cardboard(props) {
  const { nodes, materials } = useGLTF("/cardboard.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.56, 0, 0]} scale={0.03}>
        <mesh
          geometry={nodes.box_00_box_00_material_0.geometry}
          material={materials.box_00_material}
          rotation={[-Math.PI, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cardboard.gltf");
