/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 keyring.gltf
Author: eucocker (https://sketchfab.com/eucocker)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/key-a4aca11a2259462f8735a60eead33962
Title: Key
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Keyring(props) {
  const { nodes, materials } = useGLTF("/keyring.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        scale={0.005}
        geometry={nodes.Object_2.geometry}
        position={[4, 0, 3]}
        material={materials.material}
        rotation={[Math.PI / 2, Math.PI / 2, Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/keyring.gltf");
