/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 note.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Note(props) {
  const { nodes, materials } = useGLTF("/note.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.ppPaper.geometry}
        material={materials.blinn1SG}
        rotation={[0.59, -0.3, -1.36]}
        scale={0.2}
      />
    </group>
  );
}

useGLTF.preload("/note.gltf");
