/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 vessel.gltf
Author: chiwei (https://sketchfab.com/chiwei2333)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/noble-wine-vessel-4k-bakematerialtest-fb530fc7d0b148119de1977f9f5f333f
Title: Noble Wine Vessel-4K-BakeMaterialTest
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Vessel(props) {
  const { nodes, materials } = useGLTF("/vessel.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.2}>
        <mesh geometry={nodes.zun_low_zun_t_0.geometry} material={materials.zun_t} />
        <mesh geometry={nodes.zun_low_zun_t_0_1.geometry} material={materials.zun_t} />
      </group>
    </group>
  );
}

useGLTF.preload("/vessel.gltf");
