/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 woodenbox.gltf
Author: Shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-box-26bd77c0972144e9b1fa47dfc0bff334
Title: Wooden box
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Woodenbox(props) {
  const { nodes, materials } = useGLTF("/woodenbox.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.56, 0, 0]} scale={0.1}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material}
          rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/woodenbox.gltf");
